MODEL_DATABASE = {
    "ACURA": ["MDX", "RDX", "TLX", "ILX", "RL", "TSX", "ZDX", "NSX", "Integra", "RSX", "TL", "CL"],
    "ALFA ROMEO": ["Giulia", "Stelvio", "Giulietta", "MiTo", "159", "156", "147", "166", "Brera", "GT", "Spider", "Tonale", "4C", "8C"],
    "ASTON MARTIN": ["DB9", "DB11", "Vantage", "Rapide", "DBS", "Vanquish", "DBX", "Virage"],
    "AUDI": ["A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "Q2", "Q3", "Q4 e-tron", "Q5", "Q7", "Q8", "TT", "R8", "E-tron", "E-tron GT", "RS3", "RS4", "RS5", "RS6", "RS7", "S3", "S4", "S5", "S8", "SQ5", "SQ7", "SQ8", "Allroad", "80", "90", "100", "200", "V8"],
    "BENTLEY": ["Continental GT", "Flying Spur", "Bentayga", "Mulsanne", "Arnage", "Azure", "Brooklands"],
    "BMW": ["1-Series", "2-Series", "3-Series", "4-Series", "5-Series", "6-Series", "7-Series", "8-Series", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "XM", "Z3", "Z4", "Z8", "M2", "M3", "M4", "M5", "M6", "M8", "I3", "I4", "IX", "I7", "I8", "iX3"],
    "BUICK": ["Encore", "Enclave", "Regal", "LaCrosse", "Verano", "Riviera", "Park Avenue"],
    "BYD": ["Han", "Tang", "Song", "Qin", "Dolphin", "Seal", "Yuan", "F3", "F6"],
    "CADILLAC": ["Escalade", "CTS", "ATS", "XTS", "XT4", "XT5", "XT6", "SRX", "CT6", "CT5", "CT4", "Lyriq", "DeVille", "Seville", "Eldorado", "BLS"],
    "CHERY": ["Tiggo 2", "Tiggo 4", "Tiggo 7", "Tiggo 8", "Amulet", "QQ", "Eastar", "Kimo", "Beat", "Elara", "Jaggi"],
    "CHEVROLET": ["Aveo", "Lacetti", "Cruze", "Malibu", "Camaro", "Corvette", "Tahoe", "Suburban", "Spark", "Captiva", "Epica", "Evanda", "Trax", "Equinox", "Bolt", "Volt", "Niva", "Impala", "Blazer", "Orlando", "Tracker", "Cavalier", "HHR"],
    "CHRYSLER": ["300C", "200", "Pacifica", "Voyager", "Grand Voyager", "Sebring", "Town & Country", "PT Cruiser", "Crossfire", "Neon", "Stratus", "LHS", "Concorde"],
    "CITROEN": ["C1", "C2", "C3", "C3 Aircross", "C4", "C4 Cactus", "C4 Picasso", "C5", "C5 Aircross", "C6", "C8", "C-Elysée", "Berlingo", "Jumpy", "Jumper", "Nemo", "Xsara", "Xsara Picasso", "Saxo", "Xantia", "DS3", "DS4", "DS5", "BX", "XM"],
    "CUPRA": ["Formentor", "Leon", "Ateca", "Born"],
    "DACIA": ["Logan", "Sandero", "Duster", "Dokker", "Lodgy", "Spring", "Jogger", "Solenza"],
    "DAEWOO": ["Lanos", "Matiz", "Nexia", "Nubira", "Leganza", "Espero", "Tico", "Gentra", "Sens"],
    "DAIHATSU": ["Terios", "Sirion", "Cuore", "Materia", "Charade", "Copen"],
    "DODGE": ["Challenger", "Charger", "Durango", "Ram", "Journey", "Dart", "Avenger", "Caliber", "Nitro", "Magnum", "Viper", "Stratus", "Neon", "Caravan", "Grand Caravan"],
    "DS": ["DS 3", "DS 4", "DS 7 Crossback", "DS 9", "DS 5"],
    "FERRARI": ["488", "458", "F8", "Roma", "Portofino", "California", "FF", "GTC4Lusso", "812 Superfast", "F430", "360", "599", "Enzo", "LaFerrari", "SF90"],
    "FIAT": ["500", "500L", "500X", "Panda", "Tipo", "Punto", "Grande Punto", "Bravo", "Doblo", "Ducato", "Scudo", "Fiorino", "Linea", "Albea", "Croma", "Multipla", "Stilo", "Uno", "Tempra", "Fullback", "Qubo"],
    "FORD": ["Focus", "Fiesta", "Mondeo", "Fusion", "Kuga", "Escape", "Explorer", "Edge", "Mustang", "Mustang Mach-E", "Ranger", "F-150", "Transit", "Transit Custom", "Transit Connect", "Tourneo", "Puma", "EcoSport", "B-Max", "C-Max", "S-Max", "Galaxy", "Scorpio", "Sierra", "Escort", "Ka", "Maverick", "Bronco", "Taurus", "Probe"],
    "GEELY": ["Emgrand 7", "Emgrand X7", "Atlas", "Coolray", "CK", "MK", "MK Cross", "LC", "FC", "GC6", "Tugella", "Monjaro"],
    "GENESIS": ["G70", "G80", "G90", "GV70", "GV80", "GV60"],
    "GMC": ["Yukon", "Sierra", "Acadia", "Terrain", "Envoy", "Savana"],
    "GREAT WALL": ["Haval", "Wingle", "Hover", "Voleex", "Safe", "Pegasus"],
    "HAVAL": ["H2", "H6", "H9", "Jolion", "Dargo"],
    "HONDA": ["Civic", "Accord", "CR-V", "HR-V", "Jazz", "Fit", "Pilot", "Odyssey", "Insight", "Crosstour", "Element", "Ridgeline", "Legend", "Prelude", "S2000", "Stream", "FR-V", "Integra", "CR-X", "e:NS1"],
    "HUMMER": ["H1", "H2", "H3"],
    "HYUNDAI": ["Accent", "Elantra", "Sonata", "Tucson", "Santa Fe", "Grand Santa Fe", "Kona", "Ioniq", "Ioniq 5", "Ioniq 6", "I10", "I20", "I30", "I40", "Creta", "Getz", "Matrix", "Terracan", "Veracruz", "Veloster", "Tiburon", "Coupe", "H-1", "Staria", "Trajet", "Galloper", "Atos", "Palisade", "Venue"],
    "INFINITI": ["Q50", "Q60", "Q70", "QX30", "QX50", "QX55", "QX60", "QX70", "QX80", "FX35", "FX37", "FX45", "FX50", "EX25", "EX35", "G25", "G35", "G37", "M35", "M37", "QX4", "QX56", "J30"],
    "ISUZU": ["D-Max", "Trooper", "Rodeo", "VehiCROSS"],
    "JAGUAR": ["XE", "XF", "XJ", "F-Pace", "E-Pace", "I-Pace", "F-Type", "XK", "X-Type", "S-Type", "XJS"],
    "JEEP": ["Grand Cherokee", "Cherokee", "Wrangler", "Compass", "Renegade", "Patriot", "Liberty", "Commander", "Gladiator", "Wagoneer"],
    "KIA": ["Sportage", "Rio", "Ceed", "ProCeed", "XCeed", "Optima", "K5", "Sorento", "Mohave", "Soul", "Stonic", "Niro", "EV6", "EV9", "Stinger", "Picanto", "Carnival", "Carens", "Cerato", "Magentis", "Opirus", "Venga", "Shuma", "Sephia", "Clarus", "Telluride", "Seltos"],
    "LAMBORGHINI": ["Urus", "Huracan", "Aventador", "Gallardo", "Murcielago", "Diablo"],
    "LANCIA": ["Delta", "Ypsilon", "Thema", "Voyager", "Musa", "Lybra", "Kappa", "Dedra", "Phedra"],
    "LAND ROVER": ["Range Rover", "Range Rover Sport", "Range Rover Velar", "Range Rover Evoque", "Discovery", "Discovery Sport", "Defender", "Freelander"],
    "LEXUS": ["IS", "ES", "GS", "LS", "NX", "RX", "GX", "LX", "UX", "RC", "LC", "CT", "SC", "RZ", "LM"],
    "LINCOLN": ["Navigator", "Aviator", "Corsair", "Nautilus", "MKZ", "MKX", "MKC", "MKS", "MKT", "Town Car", "Continental"],
    "MASERATI": ["Ghibli", "Levante", "Quattroporte", "GranTurismo", "GranCabrio", "Grecale", "MC20"],
    "MAZDA": ["Mazda2", "Mazda3", "Mazda5", "Mazda6", "CX-3", "CX-30", "CX-5", "CX-7", "CX-9", "CX-60", "CX-90", "MX-5", "MX-30", "RX-8", "RX-7", "323", "626", "929", "Premacy", "MPV", "Xedos 6", "Xedos 9", "Tribute", "BT-50"],
    "MCLAREN": ["720S", "570S", "GT", "Artura", "P1", "650S", "MP4-12C"],
    "MERCEDES-BENZ": ["A-Class", "B-Class", "C-Class", "CLA", "CLS", "E-Class", "EQA", "EQB", "EQC", "EQE", "EQS", "G-Class", "GL-Class", "GLA", "GLB", "GLC", "GLE", "GLK", "GLS", "M-Class", "R-Class", "S-Class", "SL", "SLK", "SLC", "SLS", "AMG GT", "V-Class", "Viano", "Vito", "Sprinter", "Citan", "X-Class", "190", "W123", "W124", "CLK", "CL", "Maybach"],
    "MG": ["ZS", "HS", "Marvel R", "MG4", "MG5", "3", "6", "ZT", "F", "TF"],
    "MINI": ["Cooper", "Cooper S", "One", "Clubman", "Countryman", "Paceman", "Cabrio", "Coupe", "Roadster"],
    "MITSUBISHI": ["Lancer", "Lancer Evolution", "Outlander", "Outlander XL", "ASX", "Pajero", "Pajero Sport", "Pajero Wagon", "L200", "Eclipse", "Eclipse Cross", "Galant", "Colt", "Grandis", "Space Star", "Space Wagon", "Space Runner", "Carisma", "3000GT", "Mirage", "i-MiEV"],
    "NISSAN": ["Qashqai", "X-Trail", "Juke", "Leaf", "Micra", "Note", "Patrol", "Navara", "Murano", "Pathfinder", "Rogue", "Sentra", "Tiida", "Teana", "Altima", "Maxima", "Primera", "Almera", "Almera Classic", "Sunny", "Terrano", "GT-R", "350Z", "370Z", "Titan", "Armada", "Kicks", "Ariya", "NV200", "Quest"],
    "OPEL": ["Astra", "Vectra", "Corsa", "Insignia", "Zafira", "Meriva", "Mokka", "Crossland", "Grandland", "Vivaro", "Movano", "Combo", "Omega", "Frontera", "Monterey", "Tigra", "Calibra", "Kadett", "Ascona", "Rekord", "Senator", "Adam", "Karl", "Antara", "Signum", "Sintra"],
    "PEUGEOT": ["107", "108", "206", "207", "208", "301", "307", "308", "406", "407", "408", "508", "607", "2008", "3008", "4007", "4008", "5008", "Rifter", "Traveller", "Expert", "Boxer", "Partner", "Bipper", "RCZ", "106", "205", "306", "309", "405", "605", "806", "807", "Ion"],
    "PONTIAC": ["Vibe", "Firebird", "Grand Am", "Bonneville", "GTO", "Trans Sport", "Solstice", "G6"],
    "PORSCHE": ["Cayenne", "Macan", "Panamera", "Taycan", "911", "718 Boxster", "718 Cayman", "Boxster", "Cayman", "Carrera GT", "918 Spyder", "924", "944", "928", "968"],
    "RAVON": ["R2", "R3", "R4", "Gentra", "Matiz"],
    "RENAULT": ["Megane", "Clio", "Logan", "Sandero", "Sandero Stepway", "Duster", "Captur", "Arkana", "Kadjar", "Koleos", "Talisman", "Laguna", "Scenic", "Grand Scenic", "Espace", "Kangoo", "Trafic", "Master", "Dokker", "Zoe", "Twingo", "Fluence", "Symbol", "Modus", "Vel Satis", "Safrane", "19", "21", "25", "Twizy", "Austral"],
    "ROLLS-ROYCE": ["Phantom", "Ghost", "Wraith", "Dawn", "Cullinan", "Silver Seraph", "Corniche"],
    "ROVER": ["25", "45", "75", "200", "400", "600", "800", "Streetwise", "Mini"],
    "SAAB": ["9-3", "9-5", "900", "9000", "9-2X", "9-4X", "9-7X"],
    "SEAT": ["Ibiza", "Leon", "Arona", "Ateca", "Tarraco", "Altea", "Altea XL", "Toledo", "Cordoba", "Alhambra", "Mii", "Exeo", "Arosa", "Inca"],
    "SKODA": ["Octavia", "Octavia Tour", "Fabia", "Superb", "Kodiaq", "Karoq", "Kamiq", "Rapid", "Scala", "Yeti", "Roomster", "Citigo", "Enyaq", "Felicia", "Favorit", "Forman", "Praktik"],
    "SMART": ["Fortwo", "Forfour", "Roadster", "Smart #1"],
    "SSANGYONG": ["Rexton", "Kyron", "Actyon", "Actyon Sports", "Korando", "Tivoli", "Rodius", "Musso", "XLV"],
    "SUBARU": ["Forester", "Outback", "Legacy", "Impreza", "XV", "Crosstrek", "WRX", "WRX STI", "BRZ", "Tribeca", "Levorg", "Justy", "Baja", "Solterra"],
    "SUZUKI": ["Vitara", "Grand Vitara", "SX4", "S-Cross", "Swift", "Jimny", "Ignis", "Baleno", "Alto", "Splash", "Liana", "Kizashi", "Samurai", "Wagon R", "XL7"],
    "TESLA": ["Model S", "Model 3", "Model X", "Model Y", "Cybertruck", "Roadster"],
    "TOYOTA": ["Camry", "Corolla", "RAV4", "Land Cruiser 100", "Land Cruiser 200", "Land Cruiser 300", "Land Cruiser Prado", "Hilux", "Prius", "Yaris", "Yaris Cross", "Auris", "C-HR", "Highlander", "Avensis", "Venza", "Sequoia", "Tundra", "Tacoma", "Sienna", "Alphard", "Fortuner", "Aygo", "GT86", "Supra", "Celica", "MR2", "Carina", "Corona", "Cressida", "Previa", "Verso", "IQ", "bZ4X", "Proace"],
    "VOLKSWAGEN": ["Golf", "Golf Plus", "Passat", "Passat CC", "Jetta", "Tiguan", "Touareg", "Polo", "Arteon", "T-Roc", "T-Cross", "Taigo", "ID.3", "ID.4", "ID.5", "ID.6", "ID.Buzz", "Scirocco", "Beetle", "New Beetle", "Touran", "Sharan", "Caddy", "Transporter", "Multivan", "Caravelle", "Crafter", "Amarok", "Bora", "Vento", "Lupo", "Fox", "Up", "Phaeton", "Eos", "Corrado", "Atlas", "Teramont"],
    "VOLVO": ["S40", "S60", "S80", "S90", "V40", "V50", "V60", "V70", "V90", "XC40", "XC60", "XC70", "XC90", "C30", "C70", "C40", "EX30", "EX90", "850", "740", "940", "960", "240"],
    "ZAZ": ["Lanos", "Sens", "Forza", "Vida", "Tavria", "Slavuta", "Dana"],
    "LADA": ["Vesta", "Granta", "XRAY", "Largus", "Priora", "Kalina", "Niva", "4x4", "Samara", "2101", "2106", "2107", "2108", "2109", "21099", "2110", "2112", "2114", "2115"],
    "OTHER": ["Інша модель", "Ретро автомобіль", "Саморобний", "Спорткар"]
}

BRAND_MAPPING = {
    "VW": "VOLKSWAGEN",
    "VOLKSWAGEN": "VOLKSWAGEN",
    "MB": "MERCEDES-BENZ",
    "MERCEDES": "MERCEDES-BENZ",
    "MERCEDES-BENZ": "MERCEDES-BENZ",
    "BMW": "BMW",
    "B.M.W.": "BMW",
    "B.M.W": "BMW",
    "AUDI": "AUDI",
    "A.U.D.I.": "AUDI",
    "RANGE ROVER": "LAND ROVER",
    "LANDROVER": "LAND ROVER",
    "CHEVY": "CHEVROLET",
    "SUBARU": "SUBARU",
    "TOYOTA": "TOYOTA",
    "ZAZ": "ZAZ",
    "TESLA": "TESLA",
    "PORSCHE": "PORSCHE",
    "VAZ": "LADA",
    "LADA": "LADA",
}
# Автоматичне заповнення мапінгу
for brand_name in MODEL_DATABASE.keys():
    if brand_name not in BRAND_MAPPING:
        BRAND_MAPPING[brand_name] = brand_name

ALLOWED_COLORS = [
    "Чорний", "Білий", "Сірий", "Синій",
    "Червоний", "Зелений", "Коричневий", "Інший"
]

FUEL_TYPES = ["Бензин", "Дизель", "Газ", "Електро", "Гібрид"]


