MODEL_DATABASE = {
    "ACURA": ["MDX", "RDX", "TLX", "ILX", "RL", "TSX", "ZDX", "NSX", "INTEGRA", "RSX", "TL", "CL"],
    "ALFA ROMEO": ["GIULIA", "STELVIO", "GIULIETTA", "MITO", "159", "156", "147", "166", "BRERA", "GT", "SPIDER", "TONALE", "4C", "8C"],
    "ASTON MARTIN": ["DB9", "DB11", "VANTAGE", "RAPIDE", "DBS", "VANQUISH", "DBX", "VIRAGE"],
    "AUDI": ["A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "Q2", "Q3", "Q4 E-TRON", "Q5", "Q7", "Q8", "TT", "R8", "E-TRON", "E-TRON GT", "RS3", "RS4", "RS5", "RS6", "RS7", "S3", "S4", "S5", "S8", "SQ5", "SQ7", "SQ8", "ALLROAD", "80", "90", "100", "200", "V8"],
    "BENTLEY": ["CONTINENTAL GT", "FLYING SPUR", "BENTAYGA", "MULSANNE", "ARNAGE", "AZURE", "BROOKLANDS"],
    "BMW": ["1-SERIES", "2-SERIES", "3-SERIES", "4-SERIES", "5-SERIES", "6-SERIES", "7-SERIES", "8-SERIES", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "XM", "Z3", "Z4", "Z8", "M2", "M3", "M4", "M5", "M6", "M8", "I3", "I4", "IX", "I7", "I8", "IX3"],
    "BUICK": ["ENCORE", "ENCLAVE", "REGAL", "LACROSSE", "VERANO", "RIVIERA", "PARK AVENUE"],
    "BYD": ["HAN", "TANG", "SONG", "QIN", "DOLPHIN", "SEAL", "YUAN", "F3", "F6"],
    "CADILLAC": ["ESCALADE", "CTS", "ATS", "XTS", "XT4", "XT5", "XT6", "SRX", "CT6", "CT5", "CT4", "LYRIQ", "DEVILLE", "SEVILLE", "ELDORADO", "BLS"],
    "CHERY": ["TIGGO 2", "TIGGO 4", "TIGGO 7", "TIGGO 8", "AMULET", "QQ", "EASTAR", "KIMO", "BEAT", "ELARA", "JAGGI"],
    "CHEVROLET": ["AVEO", "LACETTI", "CRUZE", "MALIBU", "CAMARO", "CORVETTE", "TAHOE", "SUBURBAN", "SPARK", "CAPTIVA", "EPICA", "EVANDA", "TRAX", "EQUINOX", "BOLT", "VOLT", "NIVA", "IMPALA", "BLAZER", "ORLANDO", "TRACKER", "CAVALIER", "HHR"],
    "CHRYSLER": ["300C", "200", "PACIFICA", "VOYAGER", "GRAND VOYAGER", "SEBRING", "TOWN & COUNTRY", "PT CRUISER", "CROSSFIRE", "NEON", "STRATUS", "LHS", "CONCORDE"],
    "CITROEN": ["C1", "C2", "C3", "C3 AIRCROSS", "C4", "C4 CACTUS", "C4 PICASSO", "C5", "C5 AIRCROSS", "C6", "C8", "C-ELYSÉE", "BERLINGO", "JUMPY", "JUMPER", "NEMO", "XSARA", "XSARA PICASSO", "SAXO", "XANTIA", "DS3", "DS4", "DS5", "BX", "XM"],
    "CUPRA": ["FORMENTOR", "LEON", "ATECA", "BORN"],
    "DACIA": ["LOGAN", "SANDERO", "DUSTER", "DOKKER", "LODGY", "SPRING", "JOGGER", "SOLENZA"],
    "DAEWOO": ["LANOS", "MATIZ", "NEXIA", "NUBIRA", "LEGANZA", "ESPERO", "TICO", "GENTRA", "SENS"],
    "DAIHATSU": ["TERIOS", "SIRION", "CUORE", "MATERIA", "CHARADE", "COPEN"],
    "DODGE": ["CHALLENGER", "CHARGER", "DURANGO", "RAM", "JOURNEY", "DART", "AVENGER", "CALIBER", "NITRO", "MAGNUM", "VIPER", "STRATUS", "NEON", "CARAVAN", "GRAND CARAVAN"],
    "DS": ["DS 3", "DS 4", "DS 7 CROSSBACK", "DS 9", "DS 5"],
    "FERRARI": ["488", "458", "F8", "ROMA", "PORTOFINO", "CALIFORNIA", "FF", "GTC4LUSSO", "812 SUPERFAST", "F430", "360", "599", "ENZO", "LAFERRARI", "SF90"],
    "FIAT": ["500", "500L", "500X", "PANDA", "TIPO", "PUNTO", "GRANDE PUNTO", "BRAVO", "DOBLO", "DUCATO", "SCUDO", "FIORINO", "LINEA", "ALBEA", "CROMA", "MULTIPLA", "STILO", "UNO", "TEMPRA", "FULLBACK", "QUBO"],
    "FORD": ["FOCUS", "FIESTA", "MONDEO", "FUSION", "KUGA", "ESCAPE", "EXPLORER", "EDGE", "MUSTANG", "MUSTANG MACH-E", "RANGER", "F-150", "TRANSIT", "TRANSIT CUSTOM", "TRANSIT CONNECT", "TOURNEO", "PUMA", "ECOSPORT", "B-MAX", "C-MAX", "S-MAX", "GALAXY", "SCORPIO", "SIERRA", "ESCORT", "KA", "MAVERICK", "BRONCO", "TAURUS", "PROBE"],
    "GEELY": ["EMGRAND 7", "EMGRAND X7", "ATLAS", "COOLRAY", "CK", "MK", "MK CROSS", "LC", "FC", "GC6", "TUGELLA", "MONJARO"],
    "GENESIS": ["G70", "G80", "G90", "GV70", "GV80", "GV60"],
    "GMC": ["YUKON", "SIERRA", "ACADIA", "TERRAIN", "ENVOY", "SAVANA"],
    "GREAT WALL": ["HAVAL", "WINGLE", "HOVER", "VOLEEX", "SAFE", "PEGASUS"],
    "HAVAL": ["H2", "H6", "H9", "JOLION", "DARGO"],
    "HONDA": ["CIVIC", "ACCORD", "CR-V", "HR-V", "JAZZ", "FIT", "PILOT", "ODYSSEY", "INSIGHT", "CROSSTOUR", "ELEMENT", "RIDGELINE", "LEGEND", "PRELUDE", "S2000", "STREAM", "FR-V", "INTEGRA", "CR-X", "E:NS1"],
    "HUMMER": ["H1", "H2", "H3"],
    "HYUNDAI": ["ACCENT", "ELANTRA", "SONATA", "TUCSON", "SANTA FE", "GRAND SANTA FE", "KONA", "IONIQ", "IONIQ 5", "IONIQ 6", "I10", "I20", "I30", "I40", "CRETA", "GETZ", "MATRIX", "TERRACAN", "VERACRUZ", "VELOSTER", "TIBURON", "COUPE", "H-1", "STARIA", "TRAJET", "GALLOPER", "ATOS", "PALISADE", "VENUE"],
    "INFINITI": ["Q50", "Q60", "Q70", "QX30", "QX50", "QX55", "QX60", "QX70", "QX80", "FX35", "FX37", "FX45", "FX50", "EX25", "EX35", "G25", "G35", "G37", "M35", "M37", "QX4", "QX56", "J30"],
    "ISUZU": ["D-MAX", "TROOPER", "RODEO", "VEHICROSS"],
    "JAGUAR": ["XE", "XF", "XJ", "F-PACE", "E-PACE", "I-PACE", "F-TYPE", "XK", "X-TYPE", "S-TYPE", "XJS"],
    "JEEP": ["GRAND CHEROKEE", "CHEROKEE", "WRANGLER", "COMPASS", "RENEGADE", "PATRIOT", "LIBERTY", "COMMANDER", "GLADIATOR", "WAGONEER"],
    "KIA": ["SPORTAGE", "RIO", "CEED", "PROCEED", "XCEED", "OPTIMA", "K5", "SORENTO", "MOHAVE", "SOUL", "STONIC", "NIRO", "EV6", "EV9", "STINGER", "PICANTO", "CARNIVAL", "CARENS", "CERATO", "MAGENTIS", "OPIRUS", "VENGA", "SHUMA", "SEPHIA", "CLARUS", "TELLURIDE", "SELTOS"],
    "LAMBORGHINI": ["URUS", "HURACAN", "AVENTADOR", "GALLARDO", "MURCIELAGO", "DIABLO"],
    "LANCIA": ["DELTA", "YPSILON", "THEMA", "VOYAGER", "MUSA", "LYBRA", "KAPPA", "DEDRA", "PHEDRA"],
    "LAND ROVER": ["RANGE ROVER", "RANGE ROVER SPORT", "RANGE ROVER VELAR", "RANGE ROVER EVOQUE", "DISCOVERY", "DISCOVERY SPORT", "DEFENDER", "FREELANDER"],
    "LEXUS": ["IS", "ES", "GS", "LS", "NX", "RX", "GX", "LX", "UX", "RC", "LC", "CT", "SC", "RZ", "LM"],
    "LINCOLN": ["NAVIGATOR", "AVIATOR", "CORSAIR", "NAUTILUS", "MKZ", "MKX", "MKC", "MKS", "MKT", "TOWN CAR", "CONTINENTAL"],
    "MASERATI": ["GHIBLI", "LEVANTE", "QUATTROPORTE", "GRANTURISMO", "GRANCABRIO", "GRECALE", "MC20"],
    "MAZDA": ["MAZDA2", "MAZDA3", "MAZDA5", "MAZDA6", "CX-3", "CX-30", "CX-5", "CX-7", "CX-9", "CX-60", "CX-90", "MX-5", "MX-30", "RX-8", "RX-7", "323", "626", "929", "PREMACY", "MPV", "XEDOS 6", "XEDOS 9", "TRIBUTE", "BT-50"],
    "MCLAREN": ["720S", "570S", "GT", "ARTURA", "P1", "650S", "MP4-12C"],
    "MERCEDES-BENZ": ["A-CLASS", "B-CLASS", "C-CLASS", "CLA", "CLS", "E-CLASS", "EQA", "EQB", "EQC", "EQE", "EQS", "G-CLASS", "GL-CLASS", "GLA", "GLB", "GLC", "GLE", "GLK", "GLS", "M-CLASS", "R-CLASS", "S-CLASS", "SL", "SLK", "SLC", "SLS", "AMG GT", "V-CLASS", "VIANO", "VITO", "SPRINTER", "CITAN", "X-CLASS", "190", "W123", "W124", "CLK", "CL", "MAYBACH"],
    "MG": ["ZS", "HS", "MARVEL R", "MG4", "MG5", "3", "6", "ZT", "F", "TF"],
    "MINI": ["COOPER", "COOPER S", "ONE", "CLUBMAN", "COUNTRYMAN", "PACEMAN", "CABRIO", "COUPE", "ROADSTER"],
    "MITSUBISHI": ["LANCER", "LANCER EVOLUTION", "OUTLANDER", "OUTLANDER XL", "ASX", "PAJERO", "PAJERO SPORT", "PAJERO WAGON", "L200", "ECLIPSE", "ECLIPSE CROSS", "GALANT", "COLT", "GRANDIS", "SPACE STAR", "SPACE WAGON", "SPACE RUNNER", "CARISMA", "3000GT", "MIRAGE", "I-MIEV"],
    "NISSAN": ["QASHQAI", "X-TRAIL", "JUKE", "LEAF", "MICRA", "NOTE", "PATROL", "NAVARA", "MURANO", "PATHFINDER", "ROGUE", "SENTRA", "TIIDA", "TEANA", "ALTIMA", "MAXIMA", "PRIMERA", "ALMERA", "ALMERA CLASSIC", "SUNNY", "TERRANO", "GT-R", "350Z", "370Z", "TITAN", "ARMADA", "KICKS", "ARIYA", "NV200", "QUEST"],
    "OPEL": ["ASTRA", "VECTRA", "CORSA", "INSIGNIA", "ZAFIRA", "MERIVA", "MOKKA", "CROSSLAND", "GRANDLAND", "VIVARO", "MOVANO", "COMBO", "OMEGA", "FRONTERA", "MONTEREY", "TIGRA", "CALIBRA", "KADETT", "ASCONA", "REKORD", "SENATOR", "ADAM", "KARL", "ANTARA", "SIGNUM", "SINTRA"],
    "PEUGEOT": ["107", "108", "206", "207", "208", "301", "307", "308", "406", "407", "408", "508", "607", "2008", "3008", "4007", "4008", "5008", "RIFTER", "TRAVELLER", "EXPERT", "BOXER", "PARTNER", "BIPPER", "RCZ", "106", "205", "306", "309", "405", "605", "806", "807", "ION"],
    "PONTIAC": ["VIBE", "FIREBIRD", "GRAND AM", "BONNEVILLE", "GTO", "TRANS SPORT", "SOLSTICE", "G6"],
    "PORSCHE": ["CAYENNE", "MACAN", "PANAMERA", "TAYCAN", "911", "718 BOXSTER", "718 CAYMAN", "BOXSTER", "CAYMAN", "CARRERA GT", "918 SPYDER", "924", "944", "928", "968"],
    "RAVON": ["R2", "R3", "R4", "GENTRA", "MATIZ"],
    "RENAULT": ["MEGANE", "CLIO", "LOGAN", "SANDERO", "SANDERO STEPWAY", "DUSTER", "CAPTUR", "ARKANA", "Koleos", "TALISMAN", "LAGUNA", "SCENIC", "GRAND SCENIC", "ESPACE", "KANGOO", "TRAFIC", "MASTER", "DOKKER", "ZOE", "TWINGO", "FLUENCE", "SYMBOL", "MODUS", "VEL SATIS", "SAFRANE", "19", "21", "25", "TWIZY", "AUSTRAL"],
    "ROLLS-ROYCE": ["PHANTOM", "GHOST", "WRAITH", "DAWN", "CULLINAN", "SILVER SERAPH", "CORNICHE"],
    "ROVER": ["25", "45", "75", "200", "400", "600", "800", "STREETWISE", "MINI"],
    "SAAB": ["9-3", "9-5", "900", "9000", "9-2X", "9-4X", "9-7X"],
    "SEAT": ["IBIZA", "LEON", "ARONA", "ATECA", "TARRACO", "ALTEA", "ALTEA XL", "TOLEDO", "CORDOBA", "ALHAMBRA", "MII", "EXEO", "AROSA", "INCA"],
    "SKODA": ["OCTAVIA", "OCTAVIA TOUR", "FABIA", "SUPERB", "KODIAQ", "KAROQ", "KAMIQ", "RAPID", "SCALA", "YETI", "ROOMSTER", "CITIGO", "ENYAQ", "FELICIA", "FAVORIT", "FORMAN", "PRAKTIK"],
    "SMART": ["FORTWO", "FORFOUR", "ROADSTER", "SMART #1"],
    "SSANGYONG": ["REXTON", "KYRON", "ACTYON", "ACTYON SPORTS", "KORANDO", "TIVOLI", "RODIUS", "MUSSO", "XLV"],
    "SUBARU": ["FORESTER", "OUTBACK", "LEGACY", "IMPREZA", "XV", "CROSSTREK", "WRX", "WRX STI", "BRZ", "TRIBECA", "LEVORG", "JUSTY", "BAJA", "SOLTERRA"],
    "SUZUKI": ["VITARA", "GRAND VITARA", "SX4", "S-CROSS", "SWIFT", "JIMNY", "IGNIS", "BALENO", "ALTO", "SPLASH", "LIANA", "KIZASHI", "SAMURAI", "WAGON R", "XL7"],
    "TESLA": ["MODEL S", "MODEL 3", "MODEL X", "MODEL Y", "CYBERTRUCK", "ROADSTER"],
    "TOYOTA": ["CAMRY", "COROLLA", "RAV4", "LAND CRUISER 100", "LAND CRUISER 200", "LAND CRUISER 300", "LAND CRUISER PRADO", "HILUX", "PRIUS", "YARIS", "YARIS CROSS", "AURIS", "C-HR", "HIGHLANDER", "AVENSIS", "VENZA", "SEQUOIA", "TUNDRA", "TACOMA", "SIENNA", "ALPHARD", "FORTUNER", "AYGO", "GT86", "SUPRA", "CELICA", "MR2", "CARINA", "CORONA", "CRESSIDA", "PREVIA", "VERSO", "IQ", "BZ4X", "PROACE"],
    "VOLKSWAGEN": ["GOLF", "GOLF PLUS", "PASSAT", "PASSAT CC", "JETTA", "TIGUAN", "TOUAREG", "POLO", "ARTEON", "T-ROC", "T-CROSS", "TAIGO", "ID.3", "ID.4", "ID.5", "ID.6", "ID.BUZZ", "SCIROCCO", "BEETLE", "NEW BEETLE", "TOURAN", "SHARAN", "CADDY", "TRANSPORTER", "MULTIVAN", "CARAVELLE", "CRAFTER", "AMAROK", "BORA", "VENTO", "LUPO", "FOX", "UP", "PHAETON", "EOS", "CORRADO", "ATLAS", "TERAMONT"],
    "VOLVO": ["S40", "S60", "S80", "S90", "V40", "V50", "V60", "V70", "V90", "XC40", "XC60", "XC70", "XC90", "C30", "C70", "C40", "EX30", "EX90", "850", "740", "940", "960", "240"],
    "ZAZ": ["LANOS", "SENS", "FORZA", "VIDA", "TAVRIA", "SLAVUTA", "DANA"],
    "LADA": ["VESTA", "GRANTA", "XRAY", "LARGUS", "PRIORA", "KALINA", "NIVA", "4X4", "SAMARA", "2101", "2106", "2107", "2108", "2109", "21099", "2110", "2112", "2114", "2115"],
    "OTHER": ["ІНША МОДЕЛЬ", "РЕТРО АВТОМОБІЛЬ", "САМОРОБНИЙ", "СПОРТКАР"]
}

BRAND_MAPPING = {
    "VW": "VOLKSWAGEN",
    "VOLKSWAGEN": "VOLKSWAGEN",
    "MB": "MERCEDES-BENZ",
    "MERCEDES": "MERCEDES-BENZ",
    "MERCEDES-BENZ": "MERCEDES-BENZ",
    "BMW": "BMW",
    "B.M.W.": "BMW",
    "B.M.W": "BMW",
    "AUDI": "AUDI",
    "A.U.D.I.": "AUDI",
    "RANGE ROVER": "LAND ROVER",
    "LANDROVER": "LAND ROVER",
    "CHEVY": "CHEVROLET",
    "SUBARU": "SUBARU",
    "TOYOTA": "TOYOTA",
    "ZAZ": "ZAZ",
    "TESLA": "TESLA",
    "PORSCHE": "PORSCHE",
    "VAZ": "LADA",
    "LADA": "LADA",
}
# Автоматичне заповнення мапінгу
for brand_name in MODEL_DATABASE.keys():
    if brand_name not in BRAND_MAPPING:
        BRAND_MAPPING[brand_name] = brand_name

ALLOWED_COLORS = [
    "Чорний", "Білий", "Сірий", "Синій",
    "Червоний", "Зелений", "Коричневий", "Інший"
]

FUEL_TYPES = ["Бензин", "Дизель", "Газ", "Електро", "Гібрид"]

BRAND_MAPPING = {
    "VW": "VOLKSWAGEN",
    "VOLKSWAGEN": "VOLKSWAGEN",
    "MB": "MERCEDES-BENZ",
    "MERCEDES": "MERCEDES-BENZ",
    "MERCEDES-BENZ": "MERCEDES-BENZ",
    "BMW": "BMW",
    "B.M.W.": "BMW",
    "B.M.W": "BMW",
    "AUDI": "AUDI",
    "A.U.D.I.": "AUDI",
    "RANGE ROVER": "LAND ROVER",
    "LANDROVER": "LAND ROVER",
    "CHEVY": "CHEVROLET",
    "SUBARU": "SUBARU",
    "TOYOTA": "TOYOTA",
    "ZAZ": "ZAZ",
    "TESLA": "TESLA",
    "PORSCHE": "PORSCHE",
    "VAZ": "LADA",
    "LADA": "LADA",
}
# Автоматичне заповнення мапінгу
for brand_name in MODEL_DATABASE.keys():
    if brand_name not in BRAND_MAPPING:
        BRAND_MAPPING[brand_name] = brand_name

ALLOWED_COLORS = [
    "Чорний", "Білий", "Сірий", "Синій",
    "Червоний", "Зелений", "Коричневий", "Інший"
]

FUEL_TYPES = ["Бензин", "Дизель", "Газ", "Електро", "Гібрид"]


